import type { OrdenTrabajo } from "@/lib/types";

// Mock rows for the "Ordenes_Trabajo" Google Sheet tab.
// `fotos` entries simulate public Google Drive preview links; real links will
// follow the https://googleusercontent.com pattern once the Drive integration exists.
export const ordenesTrabajo: OrdenTrabajo[] = [
  {
    id: "ord-001",
    citaId: "cit-001",
    vehiculoId: "veh-001",
    estadoKanban: "Entregado",
    tipoOrden: "Reparación",
    ordenOrigenId: null,
    diagnostico: "Pastillas de freno delanteras desgastadas, se reemplazaron junto con discos.",
    kilometraje: 82340,
    combustible: "1/2",
    horaIngreso: "08:15",
    horaSalida: "16:30",
    notas: [],
    actividad: [],
    fotos: ["https://placehold.co/400x300?text=Foto+1", "https://placehold.co/400x300?text=Foto+2"],
    fechaIngreso: "2026-07-25",
    fechaEntrega: "2026-07-26",
  },
  {
    id: "ord-002",
    citaId: "cit-002",
    vehiculoId: "veh-002",
    estadoKanban: "Entregado",
    tipoOrden: "Reparación",
    ordenOrigenId: null,
    diagnostico: "Cambio de aceite sintético 5W-30 y filtro de aire.",
    kilometraje: 41200,
    combustible: "3/4",
    horaIngreso: "10:00",
    horaSalida: "11:15",
    notas: [],
    actividad: [],
    fotos: ["https://placehold.co/400x300?text=Foto+1"],
    fechaIngreso: "2026-07-27",
    fechaEntrega: "2026-07-27",
  },
  {
    id: "ord-003",
    citaId: "cit-003",
    vehiculoId: "veh-003",
    estadoKanban: "En Revisión",
    tipoOrden: "Reparación",
    ordenOrigenId: null,
    diagnostico: "Posible fuga de gas refrigerante, pendiente de confirmar con manómetro.",
    kilometraje: 96500,
    combustible: "1/4",
    horaIngreso: "13:15",
    horaSalida: null,
    notas: [],
    actividad: [],
    fotos: [],
    fechaIngreso: "2026-07-28",
    fechaEntrega: null,
  },
  {
    id: "ord-004",
    citaId: "cit-004",
    vehiculoId: "veh-004",
    estadoKanban: "Esperando Repuestos",
    tipoOrden: "Reparación",
    ordenOrigenId: null,
    diagnostico: "Sensor de oxígeno defectuoso, se ordenó repuesto original.",
    kilometraje: 63780,
    combustible: "1/2",
    horaIngreso: "09:00",
    horaSalida: null,
    notas: [],
    actividad: [],
    fotos: ["https://placehold.co/400x300?text=Foto+1"],
    fechaIngreso: "2026-07-29",
    fechaEntrega: null,
  },
  {
    id: "ord-005",
    citaId: "cit-005",
    vehiculoId: "veh-005",
    estadoKanban: "En Reparación",
    tipoOrden: "Reparación",
    ordenOrigenId: null,
    diagnostico: "Banda de tiempo con desgaste visible, reemplazo en proceso.",
    kilometraje: 74020,
    combustible: "Lleno",
    horaIngreso: "14:30",
    horaSalida: null,
    notas: [],
    actividad: [],
    fotos: [],
    fechaIngreso: "2026-07-30",
    fechaEntrega: null,
  },
  {
    id: "ord-006",
    citaId: null,
    vehiculoId: "veh-006",
    estadoKanban: "Ingresado",
    tipoOrden: "Reparación",
    ordenOrigenId: null,
    diagnostico: "",
    kilometraje: null,
    combustible: null,
    horaIngreso: "11:00",
    horaSalida: null,
    notas: [],
    actividad: [],
    fotos: [],
    fechaIngreso: "2026-07-28",
    fechaEntrega: null,
  },
];
